apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    author: intelliqit
spec:
  containers:
    - name: result-app
      image: dockersample/examplevotingapp_result
      ports:
        - containerPort: 80

